name: Glog.AI Scan

on: 
  workflow_dispatch:

jobs:
  glog-scan-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout glog-action repository
        uses: actions/checkout@v4
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/glog-action
          ref: mr/upload-issues-and-autofix

      - name: Run Glog.AI
        uses: ./.github/glog-action
        with:
          client: 'test'
          upload: 'false'
          lang: 'python'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
          env: 'dev'
          issue: 'true'
          autofix: 'true'
