# This is a basic workflow to help you get started with Actions

name: scan-ghcr

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  glog-scan-ghcr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: ghcr.io/vjelic/glog-scan-python

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Glog image
        run: docker pull ghcr.io/vjelic/glog-scan-python

      - name: Clean directories
        run: |
          [ -d $GITHUB_WORKSPACE/.glog ] && rm $GITHUB_WORKSPACE/.glog/*
          [ -d $GITHUB_WORKSPACE/.glog-log ] && rm $GITHUB_WORKSPACE/.glog-log/*

      - name: Execute scan
        run: docker run --rm -e GLOGSERVICE=0d291a03fcbfdcea699d50685a8bb27ae3b3077f -e HOST_UID=$(id -u) -e HOST_GID=$(id -g) -e IGNORE="$ignore" -v "$GITHUB_WORKSPACE":/app -v "$GITHUB_WORKSPACE/.glog:/.glog:rw" -v "$GITHUB_WORKSPACE/.glog-log:/.glog-log:rw" "ghcr.io/vjelic/glog-scan-python"
        
      - name: Commit reports
        run: |
          git config --global user.name 'vjelic'
          git config --global user.email 'jelicvladimir5@gmail.com'
          rm -f $GITHUB_WORKSPACE/.glog/glog-scan-python*.sarif
          git add .
          git commit -am "Scan executed"
          git push

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .glog/glog-scan.sarif
          category: my-analysis-tool

      # - name: List .glog-log
      #   run: ls $GITHUB_WORKSPACE/.glog-log/

      # - name: Read Glog log file
      #   run: cat /home/runner/work/vulpy/vulpy/.glog-log/glog-scan.log

      - name: Read file contents
        uses: guibranco/github-file-reader-action-v2@latest
        id: read_file
        with:
          path: ./.glog-log/glog-scan.log

      - name: File contents
        run: echo ${ steps.read_file.outputs.content }

      # - name: File size
      #   run: echo "${ steps.read_file.outputs.size }"
        
          
